In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [5]:
df=pd.read_csv("My Drive/dataset/FuelConsumption.csv")

In [6]:
df

MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [7]:
df.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [8]:
df.columns

Index(['MODELYEAR', 'MAKE', 'MODEL', 'VEHICLECLASS', 'ENGINESIZE', 'CYLINDERS',
       'TRANSMISSION', 'FUELTYPE', 'FUELCONSUMPTION_CITY',
       'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
       'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS'],
      dtype='object')

In [10]:
X=df[['ENGINESIZE']].values
Y=df['CO2EMISSIONS']

In [27]:
X

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [28]:
Y

0       196
1       221
2       136
3       255
4       244
       ... 
1062    271
1063    264
1064    271
1065    260
1066    294
Name: CO2EMISSIONS, Length: 1067, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.30,random_state=1)

In [52]:
X_test

array([[3. ],
       [1.4],
       [2. ],
       [2. ],
       [4.6],
       [3. ],
       [2. ],
       [1.8],
       [3. ],
       [2.4],
       [2.4],
       [3. ],
       [2.4],
       [5.2],
       [2.5],
       [2.5],
       [1.6],
       [4.4],
       [3.5],
       [2.4],
       [6. ],
       [2.5],
       [3.7],
       [3.5],
       [3.7],
       [3. ],
       [1.2],
       [5.5],
       [1.6],
       [2. ],
       [3. ],
       [5.2],
       [3.5],
       [5.3],
       [4. ],
       [5.3],
       [6.2],
       [1.5],
       [4.2],
       [3.3],
       [3. ],
       [6.3],
       [2. ],
       [3.6],
       [3.7],
       [2. ],
       [1.4],
       [1.4],
       [2. ],
       [3.4],
       [1.6],
       [5.7],
       [4.3],
       [6.2],
       [2. ],
       [3.7],
       [2.5],
       [5. ],
       [3.7],
       [1.6],
       [2.4],
       [2.7],
       [2. ],
       [2. ],
       [2. ],
       [1.8],
       [3.7],
       [3.6],
       [2. ],
       [1.6],
       [2. ],
      

In [53]:
Y_test

133    274
340    200
948    196
704    161
661    320
      ... 
538    294
106    292
923    368
23     230
920    262
Name: CO2EMISSIONS, Length: 321, dtype: int64

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
reg=LinearRegression()

In [56]:
reg.fit(X_train, Y_train)

LinearRegression()

In [57]:
reg.predict(X_test)

array([243.34753384, 180.59365156, 204.12635741, 204.12635741,
       306.10141612, 243.34753384, 204.12635741, 196.28212213,
       243.34753384, 219.81482799, 219.81482799, 243.34753384,
       219.81482799, 329.63412198, 223.73694563, 223.73694563,
       188.43788684, 298.25718084, 262.95812205, 219.81482799,
       361.01106312, 223.73694563, 270.80235734, 262.95812205,
       270.80235734, 243.34753384, 172.74941627, 341.40047491,
       188.43788684, 204.12635741, 243.34753384, 329.63412198,
       262.95812205, 333.55623962, 282.56871027, 333.55623962,
       368.85529841, 184.5157692 , 290.41294555, 255.11388677,
       243.34753384, 372.77741605, 204.12635741, 266.8802397 ,
       270.80235734, 204.12635741, 180.59365156, 180.59365156,
       204.12635741, 259.03600441, 188.43788684, 349.24471019,
       294.3350632 , 368.85529841, 204.12635741, 270.80235734,
       223.73694563, 321.78988669, 270.80235734, 188.43788684,
       219.81482799, 231.58118091, 204.12635741, 204.12

In [58]:
Y_test

133    274
340    200
948    196
704    161
661    320
      ... 
538    294
106    292
923    368
23     230
920    262
Name: CO2EMISSIONS, Length: 321, dtype: int64

In [59]:
reg.predict(X_test)

array([243.34753384, 180.59365156, 204.12635741, 204.12635741,
       306.10141612, 243.34753384, 204.12635741, 196.28212213,
       243.34753384, 219.81482799, 219.81482799, 243.34753384,
       219.81482799, 329.63412198, 223.73694563, 223.73694563,
       188.43788684, 298.25718084, 262.95812205, 219.81482799,
       361.01106312, 223.73694563, 270.80235734, 262.95812205,
       270.80235734, 243.34753384, 172.74941627, 341.40047491,
       188.43788684, 204.12635741, 243.34753384, 329.63412198,
       262.95812205, 333.55623962, 282.56871027, 333.55623962,
       368.85529841, 184.5157692 , 290.41294555, 255.11388677,
       243.34753384, 372.77741605, 204.12635741, 266.8802397 ,
       270.80235734, 204.12635741, 180.59365156, 180.59365156,
       204.12635741, 259.03600441, 188.43788684, 349.24471019,
       294.3350632 , 368.85529841, 204.12635741, 270.80235734,
       223.73694563, 321.78988669, 270.80235734, 188.43788684,
       219.81482799, 231.58118091, 204.12635741, 204.12

In [62]:
Y_test

133    274
340    200
948    196
704    161
661    320
      ... 
538    294
106    292
923    368
23     230
920    262
Name: CO2EMISSIONS, Length: 321, dtype: int64

In [63]:
reg.score(X_test,Y_test)

0.7672977379444554

In [64]:
reg.intercept_

125.68400456178537

In [65]:
reg.coef_

array([39.22117643])